#!/usr/bin/env bash
# ────────────────────────────────────────────────────────────────────────────
# install.sh — Build and install the nlqSearch OSD plugin
#
# Usage (run as root or with sudo):
#   sudo bash install.sh              # build, install, restart wazuh-dashboard
#   sudo bash install.sh --no-restart # build and install only; skip service restart
#
# Environment variables (optional — override defaults):
#   GEMINI_API_KEY    Gemini API key
#   NLQ_BACKEND       'gemini' or 'ollama' (default: gemini if key set)
#   GEMINI_MODEL      Gemini model name (default: gemini-2.5-flash)
#   OLLAMA_HOST       Ollama base URL (default: http://localhost:11434)
#   OLLAMA_MODEL      Ollama model (default: phi3.5)
#   INDEXER_PASSWORD  Wazuh Indexer admin password (for alert search)
# ────────────────────────────────────────────────────────────────────────────

set -euo pipefail

RESTART=1
for _arg in "$@"; do [ "$_arg" = "--no-restart" ] && RESTART=0; done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PLUGIN_ID="nlqSearch"
INSTALL_DIR="/usr/share/wazuh-dashboard/plugins/${PLUGIN_ID}"
BUILD_DIR="/tmp/${PLUGIN_ID}-build"

echo "=== nlqSearch plugin installer ==="
echo "Source : ${SCRIPT_DIR}"
echo "Build  : ${BUILD_DIR}"
echo "Target : ${INSTALL_DIR}"
echo ""

# ── 1. Check prerequisites ──────────────────────────────────────────────────
command -v node  >/dev/null 2>&1 || { echo "ERROR: node is required"; exit 1; }
command -v npm   >/dev/null 2>&1 || { echo "ERROR: npm is required";  exit 1; }

NODE_VER=$(node --version)
echo "Node : ${NODE_VER}"

# ── 2. Warn about API key ───────────────────────────────────────────────────
if [ -z "${GEMINI_API_KEY:-}" ]; then
  echo ""
  echo "WARNING: GEMINI_API_KEY is not set."
  echo "  The plugin will default to the 'ollama' backend."
  echo "  To use Gemini, set GEMINI_API_KEY before running this script:"
  echo "    export GEMINI_API_KEY=your-key && sudo -E bash install.sh"
  echo "  Or copy .env.example to .env and fill it in."
fi

# If a .env file exists in the source directory, source it to pick up vars
if [ -f "${SCRIPT_DIR}/.env" ]; then
  echo "Loading .env from ${SCRIPT_DIR}/.env"
  set -o allexport
  # shellcheck disable=SC1090
  source "${SCRIPT_DIR}/.env"
  set +o allexport
fi

# ── 3. Copy sources to /tmp to avoid vboxsf/symlink restrictions ─────────────
echo ""
echo "[1/5] Preparing build directory…"
rm -rf "${BUILD_DIR}"
cp -r "${SCRIPT_DIR}" "${BUILD_DIR}"

# ── 4. Install npm dependencies (webpack only — no runtime deps) ────────────
echo ""
echo "[2/5] Installing npm dependencies…"
cd "${BUILD_DIR}"
npm install --legacy-peer-deps 2>&1

if ! npx webpack --version >/dev/null 2>&1; then
  echo "      webpack-cli not found – installing globally…"
  npm install -g webpack-cli
fi

# ── 5. Build the public bundle ───────────────────────────────────────────────
echo ""
echo "[3/5] Building public bundle with webpack…"
cd "${BUILD_DIR}"
npx webpack --config webpack.config.js --mode production 2>&1

BUNDLE="${BUILD_DIR}/target/public/${PLUGIN_ID}.plugin.js"
if [ ! -f "${BUNDLE}" ]; then
  echo "ERROR: webpack build failed — ${PLUGIN_ID}.plugin.js not found"
  exit 1
fi
echo "      Build successful: $(du -sh "${BUNDLE}" | cut -f1) bundle"

# ── 6. Install plugin to wazuh-dashboard ────────────────────────────────────
echo ""
echo "[4/5] Copying plugin to ${INSTALL_DIR}…"

if [ -d "${INSTALL_DIR}" ]; then
  echo "      Removing existing installation…"
  rm -rf "${INSTALL_DIR}"
fi

mkdir -p "${INSTALL_DIR}"
mkdir -p "${INSTALL_DIR}/target/public"
mkdir -p "${INSTALL_DIR}/server/routes"
mkdir -p "${INSTALL_DIR}/server/lib"
mkdir -p "${INSTALL_DIR}/server/llm_backends"

# Manifest + package metadata
cp "${BUILD_DIR}/opensearch_dashboards.json" "${INSTALL_DIR}/"
cp "${BUILD_DIR}/package.json"               "${INSTALL_DIR}/"

# Server-side files (loaded by Node directly — not bundled by webpack)
cp "${BUILD_DIR}/server/index.js"                    "${INSTALL_DIR}/server/"
cp "${BUILD_DIR}/server/plugin.js"                   "${INSTALL_DIR}/server/"
cp "${BUILD_DIR}/server/routes/index.js"             "${INSTALL_DIR}/server/routes/"
cp "${BUILD_DIR}/server/lib/validator.js"            "${INSTALL_DIR}/server/lib/"
cp "${BUILD_DIR}/server/lib/transpiler.js"           "${INSTALL_DIR}/server/lib/"
cp "${BUILD_DIR}/server/lib/schema.json"             "${INSTALL_DIR}/server/lib/"
cp "${BUILD_DIR}/server/llm_backends/index.js"       "${INSTALL_DIR}/server/llm_backends/"
cp "${BUILD_DIR}/server/llm_backends/gemini.js"      "${INSTALL_DIR}/server/llm_backends/"
cp "${BUILD_DIR}/server/llm_backends/ollama.js"      "${INSTALL_DIR}/server/llm_backends/"

# Public bundle (built by webpack)
cp "${BUNDLE}" "${INSTALL_DIR}/target/public/"

# ── 7. Write environment config into the plugin's env file ──────────────────
echo ""
echo "[5a/5] Writing environment configuration…"

ENV_FILE="${INSTALL_DIR}/server/.env"
cat > "${ENV_FILE}" <<EOF
# Auto-generated by install.sh on $(date)
GEMINI_API_KEY=${GEMINI_API_KEY:-}
NLQ_BACKEND=${NLQ_BACKEND:-gemini}
GEMINI_MODEL=${GEMINI_MODEL:-gemini-2.5-flash}
OLLAMA_HOST=${OLLAMA_HOST:-http://localhost:11434}
OLLAMA_MODEL=${OLLAMA_MODEL:-phi3.5}
INDEXER_HOST=${INDEXER_HOST:-localhost}
INDEXER_PORT=${INDEXER_PORT:-9200}
INDEXER_USER=${INDEXER_USER:-admin}
INDEXER_PASSWORD=${INDEXER_PASSWORD:-}
EOF

echo "      Env file written to ${ENV_FILE}"

# Patch the routes/index.js to source the env file at runtime
# The server-side code reads from process.env; we pre-inject via a loader
cat > "${INSTALL_DIR}/server/load_env.js" <<'ENVLOADER'
'use strict';
// Loaded by plugin.js at startup — reads the .env file into process.env
const fs   = require('fs');
const path = require('path');
const envFile = path.join(__dirname, '.env');
if (fs.existsSync(envFile)) {
  const lines = fs.readFileSync(envFile, 'utf8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const val = trimmed.slice(eq + 1).trim();
    if (key && !(key in process.env)) process.env[key] = val;
  }
}
ENVLOADER

# Patch plugin.js to require load_env at the top
sed -i "s|'use strict';|'use strict';\nrequire('./load_env');|" "${INSTALL_DIR}/server/plugin.js"

# ── 8. Fix ownership ─────────────────────────────────────────────────────────
if id wazuh-dashboard >/dev/null 2>&1; then
  chown -R wazuh-dashboard:wazuh-dashboard "${INSTALL_DIR}"
fi

# Clean up build dir
rm -rf "${BUILD_DIR}"

echo "      Files installed."

# ── 9. Restart wazuh-dashboard ───────────────────────────────────────────────
echo ""
if [ "$RESTART" -eq 1 ]; then
  echo "Restarting wazuh-dashboard service…"
  if command -v systemctl >/dev/null 2>&1; then
    systemctl restart wazuh-dashboard
    sleep 4
    STATUS=$(systemctl is-active wazuh-dashboard 2>/dev/null || echo "unknown")
    echo "Service status: ${STATUS}"
  else
    echo "systemctl not found — please restart wazuh-dashboard manually."
  fi
else
  echo "Skipping service restart (--no-restart passed)."
fi

echo ""
echo "=== Installation complete ==="
echo ""
echo "Open your browser and navigate to:"
echo "  https://<wazuh-dashboard-host>/app/nlqSearch"
echo ""
echo "The plugin appears in the sidebar as 'NLQ Search'."
echo ""
if [ -z "${GEMINI_API_KEY:-}" ]; then
  echo "NOTE: Set GEMINI_API_KEY and re-run install.sh to enable the Gemini backend."
  echo "  export GEMINI_API_KEY=your-key && sudo -E bash install.sh"
fi
